spring:
  quartz:
    properties:
      org:
        quartz:
          scheduler-name: QRTZ_
          threadPool:
            threadCount: 5

          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            misfireThreshold: 60000
            useProperties: true
            dataSource: quartz

          dataSource:
            quartz:
            driver-class-name:
            url: jdbc:h2:tcp://localhost/~/quartz
            username: sa
            password:
            maxConnections: 10

    job-store-type: jdbc
    jdbc:
      initialize-schema: always


