spring:
  quartz:
    scheduler-name: QuartzScheduler
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
    job-store-type: memory

  redis:
    lettuce:
      pool:
        max-active: 5 #pool에 할당될 수 잇는 커넥션 최대수(음수로 하면 무제한)
        max-idle: 5 #pool의 idle 커넥션 최대수(음수는 무제한)
        max-wait: 2 #풀에서 관리하는 idle 커넥션의 최소 수 대상

    port: 6379
    host: 127.0.0.1
    password: 1234

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 606086322984-lusr30r8j649fjrc12ta8sagdq6nh57s.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          kakao:
            client-id: 8bd02271846053cc63735a08226924b3
            client-secret: SMvvzV3I7vhxkPnlTybcS50D1YMyfnav
            redirect-uri: http://ec2-43-201-37-71.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/kakao
            scope: #이거 때문에
              - profile_nickname
              - account_email

            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌,.

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true


  datasource:
    url: jdbc:h2:tcp://localhost/~/pillivery
    username: sa
    password:
    driver-class-name: org.h2.Driver


  config:
    activate:
      on-profile: local

logging:
  level:
#    org.apache.http: DEBUG
#    httpclient.wire: DEBUG
    org:
      springframework:
        orm:
          jpa: INFO

server:
  servlet:
    encoding:
      force-response: true

jwt:
  secret-key : sdfsdfsdfesdfdf11113456645454534545451
  # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420