spring:
  quartz:
    scheduler-name: QuartzScheduler
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
    job-store-type: memory

  redis:
    lettuce:
      pool:
        max-active: 5 #pool에 할당될 수 잇는 커넥션 최대수(음수로 하면 무제한)
        max-idle: 5 #pool의 idle 커넥션 최대수(음수는 무제한)
        max-wait: 2 #풀에서 관리하는 idle 커넥션의 최소 수 대상

    port: 6379
    host: 127.0.0.1
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true


  datasource:
    url: jdbc:h2:tcp://localhost/~/pillivery
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
#    org.apache.http: DEBUG
#    httpclient.wire: DEBUG
    org:
      springframework:
        orm:
          jpa: INFO

server:
  servlet:
    encoding:
      force-response: true



