version: 0.0

os: linux

files:
  - source: /
    destination: /home/ec2-user/instance/
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: /home/scripts/stop.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: /home/scripts/start.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: /home/scripts/health.sh
      timeout: 60
      runas: root
