version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      service:
        aliases:
          - web
    volumes:
      - ./service-url.inc:/etc/nginx/conf.d/service-url.inc
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '128m'

networks:
  service:
    driver: bridge
