spring:
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO

server:
  servlet:
    encoding:
      force-response: true

